🔢 1. NumPy Basics

Library for numerical computing

In [1]:
import numpy as np

# Create an array
arr = np.array([10, 20, 30, 40])
print("Array:", arr)

# Array operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))


Array: [10 20 30 40]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949


In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Dot product
print("Dot Product:\n", np.dot(A, B))


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Dot Product:
 [[19 22]
 [43 50]]


In [3]:
import pandas as pd

# Create DataFrame
data = {'Name': ['Nitish', 'Ravi', 'Asha'],
        'Marks': [88, 92, 79],
        'Subject': ['AI', 'ML', 'DL']}

df = pd.DataFrame(data)
print(df)


     Name  Marks Subject
0  Nitish     88      AI
1    Ravi     92      ML
2    Asha     79      DL


Read / Write CSV Files

In [4]:
# Read dataset
data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print(data.head())

# Write to CSV
data.to_csv("titanic_copy.csv", index=False)


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


Data Cleaning Operations

In [5]:
# Check missing values
print(data.isnull().sum())

# Fill missing values
data['Age'] = data['Age'].fillna(data['Age'].mean())

# Drop unnecessary columns
data = data.drop(['Cabin', 'Ticket'], axis=1)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


Filtering & Sorting

In [6]:
# Filter passengers older than 30
adults = data[data['Age'] > 30]

# Sort by Fare
sorted_data = data.sort_values(by='Fare', ascending=False)


Aggregation

In [7]:
# Average fare per class
print(data.groupby('Pclass')['Fare'].mean())


Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64


💻 3. Practice Tasks (Do on Colab)

1️⃣ Create a NumPy array of 10 random numbers and find:

Mean, Median, Std Dev, Max, Min

2️⃣ Load Titanic dataset and:

Count missing values

Replace missing Age with mean

Drop “Cabin” column

3️⃣ Filter all passengers whose Fare > 50 and Age < 30.
4️⃣ Group passengers by Pclass and find average age.

In [9]:
rand_array = np.array(np.random.randint(1,100,10))
print(rand_array)

[87 74 89 41 72 96 19 91 71 77]


In [10]:
print("Mean: ", np.mean(rand_array))
print("Median: ", np.median(rand_array))
print("Std Dev: ", np.std(rand_array))
print("Max: ", np.max(rand_array))
print("Min: ", np.min(rand_array))

Mean:  71.7
Median:  75.5
Std Dev:  22.91309669163031
Max:  96
Min:  19


In [11]:
# Load Titanic dataset
titanic_data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# Count missing values
print("Missing values before cleaning:\n", titanic_data.isnull().sum())

# Replace missing Age with mean
titanic_data['Age'] = titanic_data['Age'].fillna(titanic_data['Age'].mean())

# Drop “Cabin” column
titanic_data = titanic_data.drop('Cabin', axis=1, errors='ignore')

print("\nMissing values after cleaning:\n", titanic_data.isnull().sum())

Missing values before cleaning:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing values after cleaning:
 PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64


In [12]:
# Filter passengers whose Fare > 50 and Age < 30
filtered_passengers = titanic_data[(titanic_data['Fare'] > 50) & (titanic_data['Age'] < 30)]
print("Passengers with Fare > 50 and Age < 30:\n", filtered_passengers.head())

Passengers with Fare > 50 and Age < 30:
     PassengerId  Survived  Pclass  \
27           28         0       1   
31           32         1       1   
34           35         0       1   
72           73         0       2   
88           89         1       1   

                                              Name     Sex        Age  SibSp  \
27                  Fortune, Mr. Charles Alexander    male  19.000000      3   
31  Spencer, Mrs. William Augustus (Marie Eugenie)  female  29.699118      1   
34                         Meyer, Mr. Edgar Joseph    male  28.000000      1   
72                            Hood, Mr. Ambrose Jr    male  21.000000      0   
88                      Fortune, Miss. Mabel Helen  female  23.000000      3   

    Parch        Ticket      Fare Embarked  
27      2         19950  263.0000        S  
31      0      PC 17569  146.5208        C  
34      0      PC 17604   82.1708        C  
72      0  S.O.C. 14879   73.5000        S  
88      2         19950  263.0

In [13]:
# Group passengers by Pclass and find average age
average_age_by_pclass = titanic_data.groupby('Pclass')['Age'].mean()
print("Average Age by Pclass:\n", average_age_by_pclass)

Average Age by Pclass:
 Pclass
1    37.048118
2    29.866958
3    26.403259
Name: Age, dtype: float64
